version: 4.2
os: linux
files:
  - source: /
    destination: /opt/fit2cloud-demo/
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: configure.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: root
